application: pagefin
version: 2
runtime: python
api_version: 1
default_expiration: "30d 1h"

handlers:

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /fb/.*
  script: fb/fb.py
  
- url: /facebook/.*
  script: fb/fb.py
  
- url: /a/.*
  script: a/app.py
  
- url: /p/.*
  script: p/public.py

- url: /search/.*
  script: search/search.py
  
- url: /.*
  script: django_bootstrap.py
  
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.bat)|
 (.*/static/core/.*)|
 (\..*)|
 )$